### ISSUE TITLE
TypeError on command executed 

### ISSUE THREAD

**Issue by Anovative** [shystruk/create-react-redux-app-structure#17] opened 2018-04-17 21:26 UTC
> I get the error after running the command to create a new app instance
> However it does create a new directory `my-app` with what seems to be the desired content.

**$ create-react-redux-app-structure my-app**
```
----------------------------------------------------------
Welcome to Create React Redux App Structure
----------------------------------------------------------
Installing Packages
----------------------------------------------------------
child_process.js:381
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:381:11)
    at exports.spawn (child_process.js:494:38)
    at Object.<anonymous> (C:\Users\mrobv\AppData\Roaming\npm\node_modules\create-react-redux-app-structure\cli\cli.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
```

**Comment by shystruk** [comment] 2018-04-17 21:32
Hi @Anovative 
Thanks for being interested in create-react-redux-app-structure.

my-app was created you can use it as well. I guess the issue is on one of the npm packeges for current node version.

I close this issue as clone.
More details you may find here - https://github.com/shystruk/create-react-redux-app-structure/issues/11

**Closed by shystruk** 2018-04-17 21:32 UTC
